name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_topics: yes
          plugin_stars: yes
          plugin_habits: yes
          plugin_contributors: yes
          plugin_followup: yes
          plugin_reactions: yes
          plugin_people: yes
          plugin_stargazers: yes
          plugin_projects: yes
          plugin_code: yes
          plugin_activity: yes
          plugin_achievements: yes
          plugin_notable: yes
          plugin_gists: yes
          plugin_skyline: yes
          
